# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68600c4ff372ed4232a335f5ae25d4db72e906e24ed9ff0f14e5a6be515f9550af9b51d6de7efd3bf29908486cd6d1316d3bec1f1204bbd9355fba0bb2ba89f

test:
  secret_key_base: a3440bcd9b28857d65bb600536ac811924f542b903b9bd0e76f4697bf6f8de6a773dea0123bf54cd1e7758e4a1ce9a15f76cc5f4857d4662bd4039594e7227b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
